export const COLORS = {
  darkBlue: "#011F2B",
} as const;

export const STYLES = {
  inputNumber: {
    width: "62px",
    height: "30px",
    borderRadius: "10px",
    border: `2px solid ${COLORS.darkBlue}`,
    textAlign: "center" as const,
    fontWeight: "bold",
    fontSize: "15px",
    outline: "none",
    backgroundColor: "white",
    boxSizing: "border-box" as const,
  },
  pillBtn: (active: boolean) => ({
    padding: "6px 12px",
    borderRadius: "20px",
    border: `1.5px solid ${COLORS.darkBlue}`,
    backgroundColor: active ? COLORS.darkBlue : "transparent",
    color: active ? "white" : COLORS.darkBlue,
    cursor: "pointer",
    fontWeight: "bold",
    fontSize: "13px",
    whiteSpace: "nowrap" as const,
  }),
  main: {
    display: "flex",
    justifyContent: "center",
    padding: "32px",
    minHeight: "80vh",
  } as React.CSSProperties,
  card: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "28px",
    backgroundColor: "white",
    padding: "32px",
    borderRadius: "34px",
    border: `3px solid ${COLORS.darkBlue}`,
    maxWidth: "960px",
    width: "100%",
    alignItems: "center",
  } as React.CSSProperties,
  leftCol: {
    display: "flex",
    flexDirection: "column",
    gap: "18px",
  } as React.CSSProperties,
  box: {
    border: `2px solid ${COLORS.darkBlue}`,
    borderRadius: "26px",
    padding: "16px",
  } as React.CSSProperties,
  cta: (isSubmitting: boolean) => ({
    backgroundColor: COLORS.darkBlue,
    color: "white",
    padding: "14px",
    borderRadius: "22px",
    border: "none",
    fontWeight: "bold",
    fontSize: "16px",
    cursor: isSubmitting ? "not-allowed" : "pointer",
    width: "100%",
    letterSpacing: "1px",
    textTransform: "uppercase" as const,
    opacity: isSubmitting ? 0.75 : 1,
  }),
} as const;